### ISSUE TITLE
Medidas al medio cm

### ISSUE THREAD

**Issue by SusanaRuizPico** [Eucrow/NewCamp#11]
Intento poner incremento en Species pero luego no lo actualiza cuando quieres meter las tallas, por ejemplo Capros aper que se mide al medio cm.
También se podría explicar algo de como poner lo del incremento en Species, por ejemplo yo dudé que poner en el Capros aper, se podría meter medida cm e incremento 0.5 ó medida mm e incremento 5....

**Comment by Eucrow** [comment]
Aquí hay un bug. La idea es que el campo incremento sólo pueden ser unidades (no se pueden meter 0.5).

**Comment by Franvgls** [comment]
De hecho si las unidades son milímetros, no se deberían poder meter decimilímetros..... que no sé a qué unidad corresponde

**Comment by Eucrow** [comment]
Se ha modificado la gestión de las medidas. Se ha creado una nueva pantalla ("Measurements") para gestionar los tipos de medidas, y ahí se explica un poco cómo funciona. En esa pantalla es donde se indica el incremento y un factor de conversión que relaciona la unidad de medida con los milímetros (que es la unidad en la que se guardan las tallas en la base de datos). Ahora en las especies sólo se selecciona el tipo de medida entre las que se hayan creado en la pantalla "Measurements".
