### ISSUE TITLE
Dos veces la misma especie en Fauna List

### ISSUE THREAD

**Issue by SusanaRuizPico** [Eucrow/NewCamp#14]
Estaría bien que no dejara meter dos veces la misma especie en el listado faunístico.

**Comment by Eucrow** [comment]
En principio te deja meter la misma especie siempre y cuando metas una categoría diferente. ¿Lo puedes comprobar, porfa?

**Comment by Eucrow** [comment]
Entonces el funcionamiento es correcto :)
Gracias, cierro el issue :)
