### ISSUE TITLE
Qué es el GRID?

### ISSUE THREAD

**Issue by Franvgls** [Eucrow/NewCamp#2]
En el formulario de entrada de lances aparece grid como algo en metros, pero no sé que es.

**Comment by Franvgls** [comment]
Perdón, al ir metiendo los datos de un lance nuevo he visto que sí es la cuadrícula, pero lo dejo porque en cualquier caso no serían m y habría que definirlo como _Sampling rectangle_ o similar....

**Comment by Eucrow** [comment]
Le quito entonces la unidad y cambio el nombre a _Sampling rectangle_. Es el campo Cuadrícula del CAMP.
Pero no tiene ninguna relación con las cuadrículas ICES, ¿verdad?
