### ISSUE TITLE
Problemas en el rango de tallas 

### ISSUE THREAD

**Issue by SusanaRuizPico** [Eucrow/NewCamp#29]
En las tallas al intentar poner en Minimun length un número entre el 2 y el 9 ya no deja meter un Maximun length mayor a 10....Creo que esto ya te lo había comentado, pero me sigue pasando...igual estoy haciendo algo mal....o ya lo habías corregido....

**Comment by Eucrow** [comment]
En principio eso ya debería estar solucionado, aunque no se si la en la última versión que os envié lo tenéis ya corregido.
Si hay algún problema del que os suene que ya hay una issue creada y no la veis, recordad que puede ser que esté cerrada. Podéis ver las issues cerradas pinchando en "closed", como en la imagen que adjunto.

![image](https://github.com/Eucrow/NewCamp/assets/10269446/c6dad2d0-60ae-4e40-bf20-c9de5fa67c01)

**Comment by Eucrow** [comment]
Pues no estaba corregido, no... ahora ya si.
