### ISSUE TITLE
Faltan especies en desplegable de Fauna list

### ISSUE THREAD

**Issue by SusanaRuizPico** [Eucrow/NewCamp#33]
En Fauna List, al añadir una especie, el desplegable del grupo 1 no tiene las especies 1-Acantholabrus palloni ni 2-Alepocephalus rostratus y al final del todo aparecen 479-no estaba en el listado de especies (2) y 1-test test. Al final del desplegable del grupo 2 y 5 también hay varias especies que pone "no estaba en el listado de especies" .

**Comment by Eucrow** [comment]
Los datos de la base de datos que os pasado son de prueba. Faltarán especies, habrá alguna que he creado para probar, el tipo de medida estará cambiado... Eso no son "issues" :)

**Comment by SusanaRuizPico** [comment]
Ah perdón, pensé que era un error del desplegable, que empieza a partir de la especie 3 y me parecía raro...
