### ISSUE TITLE
Shooting, bottom and hauling

### ISSUE THREAD

**Issue by SusanaRuizPico** [Eucrow/NewCamp#6]
Cambiar el orden, bottom sería firme y hauling virada

**Comment by Eucrow** [comment]
En el estadillo vienen los siguientes campos:
largada -- shooting
firme cable -- bottom
firme aparejo
virada cable -- hauling
virada aparejo -- ¿takeoff?
arte a bordo -- onboard 

Me faltaría la traducción de firme aparejo y confirmar que la virada aparejo es takeoff. Este tema lo hablé el otro día AP y ya me comentó que tendrían que estar todos esos campos.

**Comment by Franvgls** [comment]
Confirmo, virada aparejo es takeoff como decía en algún sitio, y para firme aparejo yo diría trawling para el momento que empieza a contarse como arte en arrastre.... No sé si hay otro término más adecuado en inglés para firme, pero creo que con esto queda claro

**Comment by Eucrow** [comment]
Entonces queda así:

largada -- shooting
firme cable -- bottom
firme aparejo -- trawling
virada cable -- hauling
virada aparejo -- takeoff
arte a bordo -- onboard
