### ISSUE TITLE
Maximum length sale en rojo

### ISSUE THREAD

**Issue by SusanaRuizPico** [Eucrow/NewCamp#9]
Al meter las tallas, cuando pide el rango de tallas, meto 4 en talla mínima y al intentar meter 10 en Maximum length sale en rojo, no la coge..... no coge tallas a partir de 10...

**Comment by Eucrow** [comment]
Acabo de ver que este bug vuelve a aparecer, aunque yo juraría que lo había arreglado ya... así que reabro la issue.

**Comment by Eucrow** [comment]
Ah, nada, ya está, debió ser que vi donde estaba el error pero no lo llegué a corregir. Ahora ya está.

**Comment by SusanaRuizPico** [comment]
También pasa que en Maximum length no coge tallas mayores de 100, me pasa el meter el Coelorinchus. Supongo que estará también corregido, pero te lo comento por si acaso...
